// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD00FnZQg9OepMKdKzfDxpDenIcsiFY2nk',
    appId: '1:867766227715:web:4c0d296362197fb91b8f36',
    messagingSenderId: '867766227715',
    projectId: 'onlyucafe-ade4f',
    authDomain: 'onlyucafe-ade4f.firebaseapp.com',
    storageBucket: 'onlyucafe-ade4f.appspot.com',
    measurementId: 'G-1BPYSYYW8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANwokXGOsnAL8KVPXNp1HnCaAQalhIR28',
    appId: '1:867766227715:android:51297420c77e65cd1b8f36',
    messagingSenderId: '867766227715',
    projectId: 'onlyucafe-ade4f',
    storageBucket: 'onlyucafe-ade4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPDLiY0yaTJXj5lW5QWWLQTtQwLC-55zM',
    appId: '1:867766227715:ios:35ef42ef2d7ee8101b8f36',
    messagingSenderId: '867766227715',
    projectId: 'onlyucafe-ade4f',
    storageBucket: 'onlyucafe-ade4f.appspot.com',
    iosBundleId: 'com.example.onlyuCafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPDLiY0yaTJXj5lW5QWWLQTtQwLC-55zM',
    appId: '1:867766227715:ios:35ef42ef2d7ee8101b8f36',
    messagingSenderId: '867766227715',
    projectId: 'onlyucafe-ade4f',
    storageBucket: 'onlyucafe-ade4f.appspot.com',
    iosBundleId: 'com.example.onlyuCafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD00FnZQg9OepMKdKzfDxpDenIcsiFY2nk',
    appId: '1:867766227715:web:26215c925d845be51b8f36',
    messagingSenderId: '867766227715',
    projectId: 'onlyucafe-ade4f',
    authDomain: 'onlyucafe-ade4f.firebaseapp.com',
    storageBucket: 'onlyucafe-ade4f.appspot.com',
    measurementId: 'G-TQ42VHW98V',
  );
}
